# brew bundle
install autojump
install bash-completion
install chruby
install cloc
install ctags
install curl
install curl-ca-bundle
install docker
install dos2unix
install elasticsearch
install fuse4x
install fuse4x-kext
install git
install gnu-sed
install htop
install htop-osx
install iftop
install imagemagick
install macvim
install mysql
install memcached
install mongodb
install ncdu
install netcat
install node
install ntfs-3g
install openssl
install packer
install parallel
install pidof
install postgresql
install pstree
install qt
install readline
install reattach-to-user-namespace
install redis
install ruby-install
install sbt
install scala
install snowcrash
install sqlite
install ssh-copy-id
install sshuttle
install stow
install subversion
install tesseract
install the_silver_searcher
install tmux
install tree
install watch
install wget
install fnichol/dvm/dvm
install phinze/cask/brew-cask
